jpk3lly/Wordgame_Javascript

- game.html
- javascript/game.js
updated game HTML and javascript files so that the definition of a correct answer now shows until the next correct answer is submitted, without stopping the user from continuing to look for more words.
> updated game html and javascrit

- .vscode/settings.json
- css/game.css
Hi I have fixed the issue 
https://github.com/jpk3lly/Boggle_Hacktoberfest2023/issues/6
Thanks
> fix btn size increase issue

- javascript/end.js
added wordsIdentified content into accepted-answers div through .innerText
> add acceptedAnswers

- css/game.css
- game.html
1. Fixed Issue stated in #3 
2. Made changes to the overall game css
3. Removed unneccessary tags in game.html
> Fixed the flexbox issue and improved game ui

- css/game.css
- game.html
- javascript/game.js
Here I changed the game page css
> Boggle CSS  Issue #24

- css/game.css
- game.html
Here I tried to improve the position of containers and div for better visuals. Also the navigation bar is fixed and the body height is at max-content, so it avoids unnecessary scrolling.
> Positioning Improved

- index.html
- javascript/boggle.js
A typing animation created in the title when the page loads
[screen-capture (1).webm](https://github.com/jpk3lly/Boggle_Hacktoberfest2023/assets/22955675/f4940973-d605-436c-a860-cdd6c2096bec)
> Created a text animation for the title when the page load

- css/home.css
Fixed these issues -
The additional content of the page is hidden.
The margin of the heading is way too high.
The text overflows outside the button.
> Fix Page scrolling issues, adjust width of buttons

- css/game.css
- The keypad keeps moving up and down as the text is entered, so gave it fixed height to keep it in place.
> Gave fixed height to input display card

- css/game.css
- javascript/game.js
fixes #7 
Now, players can only select the letters which are 8 directionally adjacent to currently selected letter.
> Word Quilt Added 

- LICENSE
fixes #32 
I added the most popular license for open source MIT. You can read more [here](https://opensource.org/license/mit/) 
I am participating to hacktoberfest, can you add labels for hacktoberfest?
> Create a LICENSE for the project

- css/game.css
- game.html
- javascript/game.js
**Fixes** : #36 
**Description** :  Added the html for pop up in the game.html and the corresponding javascript in the game.js, consisting of functions to show, hide and navigate the page to index.html.
**Tags** :  `bug`, `hacktoberfest`
> Add quit CTA

- javascript/game.js
The submit button had stopped working, have fixed that and also the countdown timer had stopped working, I have fixed that too.
> Fixed submit button and clock

- .vscode/settings.json
- css/end.css
- css/game.css
- css/home.css
- css/scoreboard.css
- end.html
- tailwind.config.js
This PR uses Tailwind CSS to revamp the UI of end page. Tried not to go out of the theme of the game. Used CDN of tailwind CSS to integrate it with the project.
> Revamped the UI of end page.

- .vscode/settings.json
- css/end.css
- css/game.css
- css/home.css
- css/scoreboard.css
- end.html
- tailwind.config.js
Updates to the css have stopped the board from working correctly.
> Revert "Revamped the UI of end page."

- end.html
The event listener is added to the button using add.EventListener( ) method.
> Fixed #46 Added event listener addEventListener() method.

- css/game.css
- game.html
- resposive font size and width using clamp
- removed some inline styles and non-effective vertical align properties
- put similar styles together with comma separators
- made the borders circular
> made navbar a little more responsive

- .idea/.gitignore
- .idea/Boggle_Javascript.iml
- .idea/modules.xml
- .idea/vcs.xml
- css/game.css
- css/home.css
- css/scoreboard.css
- javascript/scoreboard.js
- scoreboard.html
Hi, i add function which save top 10 scores of players and then add this into the list which is printed on scoreboard page...i am not sure if i understand you right.  So i edit the scoreboard.js file and also scoreboard.html file.
> storageforscores

- home.css
did home page to the actual view width now it show on all screen
> did some changes in CSS

- css/home.css
- end.html
- javascript/end.js
- javascript/firebaseConfig.js
- javascript/game.js
- javascript/scoreboard.js
- scoreboard.html
fixes #8 
this uses firebase realtime database to store scores. 
if anyone wants to set this up in local machine, they have to navigate to "javascript/firebaseConfig.js" and replace the firebaseConfig as per their own configuration of firebase. for that, they need to make a new project on firebase and replace the configuration.
Hey @jpk3lly if you configure the file as i mentioned and deploy it somewhere, any user who plays in your app, top 10 user's score will be visible on the scoreboard.
Feel free to tell me, if any changes required. although the code is fully tested, feel free to test it yourself.
Thanks
> Used firebase realtime database to store scores

- javascript/game.js
Allowing the player to always deselect the last selected letter back until no letter is selected anymore.
An array is used to store the selected indexes of the letters and the last index of this array is used to enable adjacent letters. If the array is empty then all letters will be enabled.
> allowing to deselect last letter
